[project]
name = "inventory"
version = "0.1.0"
description = "Streamlit-based Inventory Management System"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.44.1",
    "pandas>=2.0.0",
]
