[project]
name = "inventory"
version = "0.1.0"
description = "Streamlit-based Inventory Management System"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit==1.24.0",
    "pandas==2.0.3",
    "json5==0.9.6",  
]